name: build on bush
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /home/githubactioner/Government-Project
          git pull
          yarn install
          yarn build
          rm -rf /var/www/html
          cp -rT /home/githubactioner/Government-Project/dist /var/www/html
