name: build on push
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          echo ***Updating Path***
          export PATH="$PATH:~/.nvm/versions/node/v19.9.0/bin/"
          echo ***Moving to Project Repo***
          cd ~/Government-Project
          echo ***Pulling***
          git pull
          echo ***Installing Node Modules***
          yarn install
          echo ***Building Project***
          yarn build
          echo ***Updating Webpages***
          rm -rf /var/www/html
          cp -rT ~/Government-Project/dist /var/www/html
